### ISSUE TITLE
Reload Button Misaligned

### ISSUE THREAD

**Issue by WenXin20** [Fuzss/menucompanions#1]
`Minecraft v1.15.2`
`Forge v32.1.36`
`Menu Companions v1.0.0`

When holding down right-ctrl, the reload button appears but is misaligned. Maybe because of the menu change also made by [lotr](https://www.curseforge.com/minecraft/mc-mods/the-lord-of-the-rings-mod-renewed)? Also, my mouse is in the center of the screen, but both the player and the bee are looking away from the mouse. And lastly, clicking on the bee instead hurts the player, while clicking the player does nothing. 
Also, is the a way to have it display a random mob from any mod without having to add them all manually?
Thanks!

![2020-10-02_12 01 49](https://user-images.githubusercontent.com/12000593/94950389-2f544200-04a8-11eb-8860-a4ebc5ab0d61.png)

**Comment by Fuzss** [comment]
Something is moving everything downwards for sure. I've added a config option to offset the button in v1.0.2.
Player and bee spazzing out is caused by the issue with Name Pain, which has now also been fixed.
For a random mob out of all currently registered set the id field to random. There is some documentation for the mobs.json file on the Curse page.

**Comment by WenXin20** [comment]
Alright, thanks!
I was looking at the mod page on mobile, so I didn't see the additional information on the side of the page.
